//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardMatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsMessage
    {
        public int MessageID { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserEmail { get; set; }
        public string MessageText { get; set; }
    }
}
