//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardMatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScore
    {
        public int ScoreID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> GameDateTime { get; set; }
        public decimal GameDuration { get; set; }
        public int GameMoves { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
